main:
  - name: Home
    url: /
    weight: 10

  - name: Principal Investigator 
    url: /pi/
    weight: 11

  - name: About
    url: /about/
    weight: 12

  - name: Publications
    url: /publications/
    weight: 13

  - name: Courses
    url: /courses/
    weight: 14

  - name: Members
    url: /members/
    weight: 15

  - name: Contact
    url: /contact/
    weight: 16

  - name: Photo
    url: /photo/
    weight: 17
